// ============================================================================
// DataReaper Tripwire Shield — Config Injector
// Run automatically by package-extension.js. NOT bundled into production builds.
// Reads GOOGLE_SAFE_BROWSING_API_KEY, SHIELD_DASHBOARD_ORIGIN, SHIELD_API_BASE
// from environment variables and writes a background-config-init.js shim that
// injects them into chrome.storage.local on extension startup.
// ============================================================================

const fs = require("fs");
const path = require("path");

const key             = process.env.GOOGLE_SAFE_BROWSING_API_KEY || "";
const dashboardOrigin = process.env.SHIELD_DASHBOARD_ORIGIN      || "http://localhost:5173";
const apiBase         = process.env.SHIELD_API_BASE               || "http://localhost:8000/api";

const shim = `
// Auto-generated by inject-config.js — DO NOT EDIT MANUALLY.
// Runs as a service worker import on extension startup to seed chrome.storage.local.
(async () => {
  await chrome.storage.local.set({
    dr_safe_browsing_key:  ${JSON.stringify(key)},
    dr_dashboard_origin:   ${JSON.stringify(dashboardOrigin)},
    dr_api_base:           ${JSON.stringify(apiBase)},
  });
  console.log("[DataReaper] Config injected into storage.");
})();
`.trimStart();

const outPath = path.join(__dirname, "background-config-init.js");
fs.writeFileSync(outPath, shim, "utf8");

console.log("[DataReaper] Config shim written → background-config-init.js");
console.log(`  Safe Browsing key : ${key ? "SET (" + key.slice(0, 8) + "...)" : "EMPTY — mock-safe mode"}`);
console.log(`  Dashboard origin  : ${dashboardOrigin}`);
console.log(`  API base          : ${apiBase}`);