/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create anonymous frontend session
         * @description Called on first app interaction to create a short-lived anonymous session.
         *     Session ID is used in X-Session-Id header for subsequent requests.
         */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Initialize new privacy scan
         * @description Triggered from onboarding when user enters one seed value (email or phone).
         *     Returns scan ID used by Command Center, Identity Graph, and War Room routes.
         */
        post: operations["createScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scans/{scanId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get scan status and high-level lifecycle state */
        get: operations["getScan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scans/{scanId}/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Command Center summary cards and trends */
        get: operations["getDashboardSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scans/{scanId}/dashboard/radar-targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get live radar targets for Command Center radar */
        get: operations["getRadarTargets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scans/{scanId}/dashboard/activity-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get activity feed logs */
        get: operations["getActivityLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scans/{scanId}/dashboard/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get autonomous agent status list */
        get: operations["getAgentStatuses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scans/{scanId}/dashboard/pivot-chain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get pivot tree data for intelligence chain graph */
        get: operations["getPivotChain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scans/{scanId}/identity-graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get identity graph nodes and edges
         * @description Supports visibility filters used by Identity Graph page:
         *     - Platforms toggle
         *     - Identity data toggle
         *     - Data broker targets toggle
         */
        get: operations["getIdentityGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scans/{scanId}/identity-graph/nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get single node detail panel data */
        get: operations["getIdentityGraphNode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scans/{scanId}/war-room/engagements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List broker engagements for left pane in War Room */
        get: operations["listEngagements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scans/{scanId}/war-room/engagements/{engagementId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get full engagement including message thread */
        get: operations["getEngagement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scans/{scanId}/war-room/engagements/{engagementId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get paginated thread messages */
        get: operations["listEngagementMessages"];
        put?: never;
        /**
         * Add manual operator note or outbound message
         * @description Optional endpoint for future manual intervention.
         *     Not currently used by the frontend but aligns with the War Room interaction model.
         */
        post: operations["createEngagementMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scans/{scanId}/war-room/engagements/{engagementId}/actions/escalate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger legal escalation on an engagement */
        post: operations["escalateEngagement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/content/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List landing resources/cards shown in final CTA section */
        get: operations["listResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/realtime/connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create realtime connection descriptor (WebSocket or SSE)
         * @description Frontend calls this once per scan route mount to receive a short-lived token and endpoint.
         *     Backend can serve ws://, wss://, or SSE endpoint.
         */
        post: operations["createRealtimeConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example scn_01JY8H3R8Y9F8S3TB3D3S9K3A1 */
        ScanId: string;
        /** @example eng_APOLLO_0001 */
        EngagementId: string;
        /**
         * Format: date-time
         * @example 2026-04-18T14:52:31Z
         */
        IsoTimestamp: string;
        /**
         * @description Human readable relative label shown in UI.
         * @example 2 min ago
         */
        RelativeTimeText: string;
        /** @enum {string} */
        SeedType: "email" | "phone";
        /** @enum {string} */
        ScanStatus: "queued" | "discovering" | "identifying" | "engaging" | "stabilizing" | "completed" | "failed";
        /** @enum {string} */
        EngagementStatus: "resolved" | "stalling" | "illegal" | "in-progress";
        /** @enum {string} */
        MessageType: "broker" | "agent" | "system";
        /** @enum {string} */
        ClassificationType: "Violation" | "Delay" | "Warning" | "Progress" | "Resolved";
        /** @enum {string} */
        ThreatType: "email" | "phone" | "location";
        /** @enum {string} */
        RadarTargetStatus: "Scanning" | "Identified" | "Deletion in progress";
        /** @enum {string} */
        ActivityLogType: "System" | "Scan" | "Match" | "Legal" | "Comm";
        /** @enum {string} */
        GraphNodeType: "seed" | "platform" | "username" | "identity" | "target";
        /** @enum {string} */
        AgentMode: "SLEUTH" | "LEGAL" | "COMMS" | "DELETION";
        CreateSessionRequest: {
            client: {
                /** @example web-1.0.0 */
                appVersion: string;
                /** @example browser */
                platform: string;
                /** @example Asia/Kolkata */
                timezone?: string;
                /** @example en-IN */
                locale?: string;
            };
        };
        CreateSessionResponse: {
            /** @example ses_01JY8GZC8QAZ6B3N3WFKAX2D56 */
            sessionId: string;
            expiresAt: components["schemas"]["IsoTimestamp"];
        };
        SeedInput: {
            type: components["schemas"]["SeedType"];
            /**
             * @description Raw email or phone value from onboarding input.
             * @example user@email.com
             */
            value: string;
            /**
             * @description Required for ambiguous phone parsing.
             * @example IN
             */
            countryCode?: string;
        };
        CreateScanRequest: {
            seed: components["schemas"]["SeedInput"];
            /** @example en-IN */
            locale?: string;
            /**
             * @default AUTO
             * @enum {string}
             */
            jurisdictionHint: "DPDP" | "GDPR" | "CCPA" | "AUTO";
        };
        CreateScanResponse: {
            scanId: components["schemas"]["ScanId"];
            status: components["schemas"]["ScanStatus"];
            startedAt: components["schemas"]["IsoTimestamp"];
            routeHints: {
                /** @example /command-center */
                commandCenter: string;
                /** @example /identity-graph */
                identityGraph: string;
                /** @example /war-room */
                warRoom: string;
            };
        };
        Scan: {
            scanId: components["schemas"]["ScanId"];
            seed: components["schemas"]["SeedInput"];
            status: components["schemas"]["ScanStatus"];
            progress: number;
            createdAt: components["schemas"]["IsoTimestamp"];
            updatedAt: components["schemas"]["IsoTimestamp"];
            failureReason?: string;
        };
        DashboardStats: {
            brokersScanned: number;
            exposuresFound: number;
            deletionsSecured: number;
            activeDisputes: number;
        };
        DashboardTrends: {
            brokersScanned: number[];
            exposuresFound: number[];
            deletionsSecured: number[];
            activeDisputes: number[];
        };
        ThreatBreakdownItem: {
            type: components["schemas"]["ThreatType"];
            count: number;
            percentOfTotal: number;
        };
        DashboardSummary: {
            scanId: components["schemas"]["ScanId"];
            stats: components["schemas"]["DashboardStats"];
            trends: components["schemas"]["DashboardTrends"];
            threatBreakdown: components["schemas"]["ThreatBreakdownItem"][];
        };
        RadarTarget: {
            id: number;
            angle: number;
            distance: number;
            /** @example DarkWeb Market */
            broker: string;
            status: components["schemas"]["RadarTargetStatus"];
            /**
             * @description Hex color to preserve frontend visual semantics.
             * @example #4a9eff
             */
            color: string;
            type: components["schemas"]["ThreatType"];
            confidence: number;
        };
        ActivityLog: {
            id: number;
            type: components["schemas"]["ActivityLogType"];
            /** @example Drafting DPDP-compliant request... */
            message: string;
            /** @example #b94a48 */
            color: string;
            createdAt: components["schemas"]["IsoTimestamp"];
        };
        ActivityLogPage: {
            items: components["schemas"]["ActivityLog"][];
            pageInfo: components["schemas"]["PageInfo"];
        };
        AgentStatus: {
            /** @example Sleuth Agent */
            name: string;
            mode: components["schemas"]["AgentMode"];
            /** @example Active */
            status: string;
            /** @example Scraping Apollo directory... */
            task: string;
            progress: number;
        };
        PivotColumn: {
            /** @enum {string} */
            label: "Emails" | "Usernames" | "Platforms" | "Brokers";
            values: string[];
        };
        PivotEdge: {
            fromColumn: number;
            fromIndex: number;
            toColumn: number;
            toIndex: number;
        };
        PivotSummaryItem: {
            label: string;
            value: number;
            max: number;
        };
        PivotChain: {
            scanId: components["schemas"]["ScanId"];
            columns: components["schemas"]["PivotColumn"][];
            edges: components["schemas"]["PivotEdge"][];
            summary: components["schemas"]["PivotSummaryItem"][];
        };
        IdentityNodeData: {
            platform?: string;
            value?: string;
            status?: string;
            details?: string[];
        };
        IdentityGraphNode: {
            /** @example identity1 */
            id: string;
            type: components["schemas"]["GraphNodeType"];
            /** @example John Doe */
            label: string;
            x: number;
            y: number;
            connections: string[];
            /** @description Optional progressive animation step index. */
            revealStep?: number;
            data?: components["schemas"]["IdentityNodeData"];
        };
        IdentityGraphEdge: {
            fromNodeId: string;
            toNodeId: string;
        };
        IdentityGraphPayload: {
            scanId: components["schemas"]["ScanId"];
            nodes: components["schemas"]["IdentityGraphNode"][];
            edges: components["schemas"]["IdentityGraphEdge"][];
            filters: {
                showPlatforms: boolean;
                showIdentity: boolean;
                showTargets: boolean;
            };
        };
        EngagementSummary: {
            id: components["schemas"]["EngagementId"];
            /** @example Apollo.io */
            brokerName: string;
            status: components["schemas"]["EngagementStatus"];
            lastActivity: components["schemas"]["RelativeTimeText"] | components["schemas"]["IsoTimestamp"];
            messageCount: number;
        };
        MessageMetadata: {
            classification?: components["schemas"]["ClassificationType"];
            /** @example Section 12(1), DPDP Act 2023 */
            legalCitation?: string;
            explanation?: string;
        };
        EngagementMessage: {
            /** @example m7 */
            id: string;
            type: components["schemas"]["MessageType"];
            content: string;
            timestamp: string | components["schemas"]["IsoTimestamp"];
            metadata?: components["schemas"]["MessageMetadata"];
        };
        EngagementDetail: components["schemas"]["EngagementSummary"] & {
            conversation: components["schemas"]["EngagementMessage"][];
        };
        MessagePage: {
            items: components["schemas"]["EngagementMessage"][];
            pageInfo: components["schemas"]["PageInfo"];
        };
        CreateMessageRequest: {
            /** @enum {string} */
            type: "agent" | "system";
            content: string;
            metadata?: components["schemas"]["MessageMetadata"];
        };
        EscalateEngagementRequest: {
            /** @enum {string} */
            reasonCode: "illegal_request" | "excessive_delay" | "non_compliance" | "partial_compliance";
            note: string;
            /**
             * @default DPDP
             * @enum {string}
             */
            legalFramework: "DPDP" | "GDPR" | "CCPA";
        };
        EscalateEngagementResponse: {
            /** @constant */
            accepted: true;
            engagementId: components["schemas"]["EngagementId"];
            queuedAt: components["schemas"]["IsoTimestamp"];
        };
        ResourceCard: {
            id: string;
            /** @example architecture */
            tag: string;
            title: string;
            /** Format: uri */
            imageUrl: string;
            /** Format: uri-reference */
            href: string;
        };
        CreateRealtimeConnectionRequest: {
            scanId: components["schemas"]["ScanId"];
            channels: ("dashboard.summary" | "dashboard.radar" | "dashboard.activity" | "dashboard.agents" | "identity.graph" | "warroom.engagements" | "warroom.messages" | "scans.lifecycle")[];
            /**
             * @default websocket
             * @enum {string}
             */
            preferredTransport: "websocket" | "sse";
        };
        CreateRealtimeConnectionResponse: {
            /** @example rtc_01JY8N3PZG6C7W76P1Z6D4QH0R */
            connectionId: string;
            /** @enum {string} */
            transport: "websocket" | "sse";
            /**
             * Format: uri
             * @example wss://api.datareaper.io/v1/realtime/ws
             */
            endpoint: string;
            /** @description Short-lived bearer used only for realtime handshake. */
            token: string;
            expiresAt: components["schemas"]["IsoTimestamp"];
        };
        PageInfo: {
            nextCursor?: string | null;
            hasMore: boolean;
        };
        ApiError: {
            /** @example invalid_seed */
            code: string;
            /** @example Seed value must be a valid email or E.164 phone number. */
            message: string;
            details?: {
                [key: string]: unknown;
            }[];
        };
    };
    responses: {
        /** @description Invalid request payload or query parameters. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Requested resource was not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Conflict with existing resource or in-progress operation. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        ScanId: components["schemas"]["ScanId"];
        EngagementId: components["schemas"]["EngagementId"];
        /** @description Opaque pagination cursor. */
        Cursor: string;
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSessionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createScan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScanRequest"];
            };
        };
        responses: {
            /** @description Scan accepted and started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateScanResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    getScan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scanId: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scan status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getDashboardSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scanId: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard summary payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getRadarTargets: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                scanId: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Radar targets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        scanId: components["schemas"]["ScanId"];
                        items: components["schemas"]["RadarTarget"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getActivityLogs: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                /** @description Optional filter by one or more log categories. */
                types?: components["schemas"]["ActivityLogType"][];
            };
            header?: never;
            path: {
                scanId: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated activity logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityLogPage"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getAgentStatuses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scanId: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent statuses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        scanId: components["schemas"]["ScanId"];
                        agents: components["schemas"]["AgentStatus"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getPivotChain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scanId: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pivot chain graph payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PivotChain"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getIdentityGraph: {
        parameters: {
            query?: {
                includePlatforms?: boolean;
                includeIdentity?: boolean;
                includeTargets?: boolean;
            };
            header?: never;
            path: {
                scanId: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Identity graph payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityGraphPayload"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getIdentityGraphNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scanId: components["parameters"]["ScanId"];
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityGraphNode"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listEngagements: {
        parameters: {
            query?: {
                /** @description Optional status filters. */
                statuses?: components["schemas"]["EngagementStatus"][];
            };
            header?: never;
            path: {
                scanId: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Engagement list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        scanId: components["schemas"]["ScanId"];
                        items: components["schemas"]["EngagementSummary"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getEngagement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scanId: components["parameters"]["ScanId"];
                engagementId: components["parameters"]["EngagementId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Engagement detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngagementDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listEngagementMessages: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                scanId: components["parameters"]["ScanId"];
                engagementId: components["parameters"]["EngagementId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Message page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createEngagementMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scanId: components["parameters"]["ScanId"];
                engagementId: components["parameters"]["EngagementId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMessageRequest"];
            };
        };
        responses: {
            /** @description Message created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngagementMessage"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    escalateEngagement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scanId: components["parameters"]["ScanId"];
                engagementId: components["parameters"]["EngagementId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EscalateEngagementRequest"];
            };
        };
        responses: {
            /** @description Escalation accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscalateEngagementResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listResources: {
        parameters: {
            query?: {
                section?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource cards */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ResourceCard"][];
                    };
                };
            };
        };
    };
    createRealtimeConnection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRealtimeConnectionRequest"];
            };
        };
        responses: {
            /** @description Realtime connection descriptor */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRealtimeConnectionResponse"];
                };
            };
        };
    };
}
